// Verbatim condition detail content, transcribed exactly as provided by the
// client (no paraphrasing or merging of subsections). Replaces the earlier,
// partially-paraphrased Vertigo/Back Pain entries and adds 6 more.
require('dotenv').config();
const connectDB = require('../config/db');
const Condition = require('../models/Condition');

const DETAILS = [
  {
    slug: 'vertigo',
    intro: 'Vertigo can feel unsettling and disruptive, often making even simple daily activities difficult. If you’re experiencing spinning sensations, dizziness, or balance issues, seeking professional care can make a meaningful difference. At Remarkable Physiotherapy in Markham, we focus on identifying the cause of vertigo and helping you restore stability and confidence in your movements.',
    whatIsIt: 'Vertigo is not just a general feeling of dizziness; it is a specific sensation that you or your surroundings are spinning or moving when there is no actual motion. This condition is commonly linked to issues within the inner ear or the vestibular system, which plays a key role in maintaining balance.',
    symptoms: ['A spinning or whirling sensation', 'Loss of balance or unsteadiness', 'Nausea or vomiting', 'Difficulty focusing or visual disturbances', 'Headaches or pressure in the head', 'Ringing in the ears (tinnitus)'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Benign Paroxysmal Positional Vertigo (BPPV)', description: 'BPPV is one of the most common causes of vertigo. It occurs when tiny calcium particles in the inner ear become displaced, leading to brief episodes of dizziness triggered by changes in head position.' },
      { title: 'Vestibular Neuritis', description: 'This condition involves inflammation of the vestibular nerve, often due to a viral infection. It can cause sudden, intense vertigo that may last several days.' },
      { title: 'Meniere’s Disease', description: 'Meniere’s disease is associated with fluid buildup in the inner ear. It can lead to recurring episodes of vertigo along with hearing loss and tinnitus.' },
      { title: 'Other Contributing Factors', description: 'Head injuries, migraines, inner ear infections, age-related balance decline.' },
    ],
    treatmentApproach: 'Physiotherapy plays a significant role in managing vertigo by addressing the underlying cause and improving the body’s balance system. At Remarkable Physiotherapy, we use targeted approaches to help reduce symptoms and restore normal movement.',
    treatmentDetails: [
      { title: 'Vestibular Rehabilitation', description: 'Vestibular rehabilitation focuses on retraining the brain and body to process balance signals correctly. This includes specific exercises that improve coordination and stability.' },
      { title: 'Canalith Repositioning Techniques', description: 'For conditions like BPPV, repositioning techniques are used to guide displaced particles in the inner ear back to their proper location. These maneuvers are gentle and often provide noticeable symptom improvement.' },
      { title: 'Balance and Coordination Training', description: 'Improving balance is key to preventing falls and regaining confidence. Structured exercises help strengthen the body’s ability to maintain stability during daily activities.' },
      { title: 'Gaze Stabilization Exercises', description: 'These exercises help improve visual focus during head movements, reducing dizziness and improving overall function.' },
      { title: 'Thorough Assessment', description: 'We evaluate your balance, coordination, and vestibular function to identify the source of your symptoms.' },
      { title: 'Individualized Care Plan', description: 'Based on your assessment, a structured plan is created to address your specific condition and goals.' },
      { title: 'Ongoing Support', description: 'Your progress is monitored closely, and adjustments are made as needed to ensure steady improvement.' },
    ],
    benefits: [],
    practicalTips: ['Vertigo episodes are recurring.', 'Symptoms interfere with daily activities.', 'You experience nausea or difficulty walking.', 'There is no improvement over time.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Focus on Root Cause', description: 'Rather than addressing only symptoms, we aim to identify and manage the underlying cause of your vertigo.' },
      { title: 'Evidence-Based Methods', description: 'Our approach is grounded in proven techniques that are widely used for vestibular conditions.' },
      { title: 'Patient-Centered Care', description: 'We take the time to listen to your concerns and adapt your care plan based on your progress and feedback.' },
      { title: 'Convenient Markham Location', description: 'Our clinic is easily accessible, making it simple for residents of Markham to receive consistent care.' },
    ],
    whenToSeekHelp: 'If you experience frequent dizziness, balance problems, or sudden episodes of spinning sensations, it is important to seek professional evaluation. Early care can help prevent worsening symptoms and reduce the risk of falls or injury. Living with vertigo can be challenging, but you don’t have to manage it alone. With the right approach, many people notice a significant reduction in symptoms and improved balance. If you’re in Markham and dealing with vertigo, contact Remarkable Physiotherapy today. Book your appointment and take the first step toward steady, confident movement.',
  },
  {
    slug: 'back-pain',
    intro: 'Back pain is one of the most common physical complaints affecting people of all ages in Markham. Whether it comes from long hours at a desk, physically demanding work, sports activities, or sudden injury, it can interfere with daily life and limit movement. At Remarkable Physiotherapy, we focus on identifying the root cause of back pain and helping you return to normal function with structured care.',
    whatIsIt: 'Back pain can occur anywhere along the spine, from the neck down to the lower back. Most cases involve the lower back, also known as the lumbar region, as it supports much of the body’s weight and movement. Common Types of Back Pain: Acute back pain – lasts a few days to a few weeks, often caused by strain or injury. Chronic back pain – persists for more than three months and may involve deeper structural issues. Mechanical back pain – related to muscles, joints, or discs. Radicular pain – caused by nerve irritation, often felt as shooting pain down the leg. Each type requires a different approach, which is why proper assessment is essential.',
    symptoms: ['Pain that persists for several days without improvement', 'Difficulty bending, twisting, or standing upright', 'Pain radiating into the legs or arms.', 'Numbness or tingling sensations', 'Stiffness after rest or in the morning'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Everyday Causes', description: 'Poor posture while sitting or standing. Prolonged screen time without breaks. Improper lifting techniques. Weak core muscles. Sedentary lifestyle.' },
      { title: 'Injury and Medical Conditions', description: 'Muscle or ligament strain. Herniated or bulging discs. Degenerative disc changes. Sciatica. Spinal joint dysfunction.' },
    ],
    treatmentApproach: 'Our clinic in Markham uses a structured approach that focuses on restoring movement, reducing discomfort, and improving overall function.',
    treatmentDetails: [
      { title: 'Thorough Assessment', description: 'We begin with a detailed evaluation of your posture, mobility, strength, and movement patterns. This helps us identify the exact source of your back pain.' },
      { title: 'Hands-On Techniques', description: 'Our therapists use manual methods to improve joint mobility and reduce muscle tension. These techniques help restore natural spinal movement.' },
      { title: 'Strength and Stability Training', description: 'Exercises are introduced to strengthen core muscles, which play a major role in supporting the spine.' },
      { title: 'Flexibility and Mobility Work', description: 'Stretching routines help reduce stiffness and improve range of motion.' },
      { title: 'Movement Re-education', description: 'We help you relearn safe movement patterns for daily activities such as sitting, lifting, and walking.' },
      { title: 'Education and Prevention', description: 'You will also receive practical advice on posture, workstation setup, and activity modification to help reduce strain on your back.' },
    ],
    benefits: ['Reduced discomfort during movement and rest', 'Improved flexibility and strength', 'Better posture and body mechanics', 'Increased ability to perform daily tasks', 'Lower risk of recurring issues'],
    practicalTips: ['Prevent the condition from worsening.', 'Reduce downtime from work or daily activities.', 'Improve recovery speed.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Individual Attention', description: 'Every session is centred around your progress, ensuring your needs are addressed at each stage.' },
      { title: 'Evidence-Based Methods', description: 'We use proven techniques backed by research to support your recovery.' },
      { title: 'Supportive Environment', description: 'Our clinic provides a welcoming and motivating space where you can focus on improving your physical health.' },
      { title: 'Focus on Lasting Results', description: 'We work to correct the underlying cause rather than just manage symptoms.' },
    ],
    whenToSeekHelp: 'Back pain should not control how you live your life. At Remarkable Physiotherapy in Markham, we are here to help you move comfortably and confidently again. If you are experiencing back pain or noticing early signs, now is the time to take action. Book an appointment with our team or contact us today to begin your journey toward improved movement and a more active lifestyle. Related Markham back pain guide: For more practical education, read our guide: Physiotherapy for Low Back Pain in Markham. If symptoms are affecting work, sleep, walking, or daily movement, you can also book an assessment with Remarkable Physiotherapy.',
  },
  {
    slug: 'wrist-pain',
    intro: 'Wrist pain can interfere with even the simplest daily tasks, from typing and lifting objects to driving and exercising. Whether your discomfort began suddenly or developed over time, addressing it early can make a significant difference. At Remarkable Physiotherapy in Markham, we focus on identifying the root cause of wrist pain and helping you return to your routine with confidence.',
    whatIsIt: 'Wrist pain refers to any discomfort, stiffness, or soreness around the wrist joint. This area is made up of small bones, ligaments, tendons, and nerves that work together to provide movement and stability. Because of its complexity, the wrist is vulnerable to strain, overuse, and injury. Pain may be mild and occasional or persistent and sharp, depending on the cause. Some people also notice swelling, weakness, or difficulty gripping objects.',
    symptoms: [],
    symptomsDetails: [
      { title: 'Persistent Pain', description: 'If wrist pain lasts more than a few days or keeps returning, it may indicate an underlying issue that needs attention.' },
      { title: 'Swelling or Stiffness', description: 'Visible swelling or difficulty moving the wrist normally can suggest tissue irritation or injury.' },
      { title: 'Weak Grip Strength', description: 'Struggling to hold objects or noticing reduced strength can affect daily activities and should be evaluated.' },
      { title: 'Numbness or Tingling', description: 'These sensations may point to nerve involvement and should not be overlooked.' },
    ],
    causes: [],
    causesDetails: [
      { title: 'Repetitive Strain Injuries', description: 'Activities that involve repeated wrist movements, such as typing, using a mouse, or working with tools, can lead to irritation in the tendons and surrounding tissues.' },
      { title: 'Sprains and Ligament Injuries', description: 'A sudden twist or fall onto an outstretched hand can stretch or tear ligaments, resulting in pain and swelling.' },
      { title: 'Tendonitis', description: 'Inflammation of the tendons often develops from overuse. It can cause discomfort during movement and may worsen over time if ignored.' },
      { title: 'Carpal Tunnel Syndrome', description: 'Pressure on the median nerve at the wrist can cause numbness, tingling, and weakness in the hand and fingers.' },
      { title: 'Arthritis', description: 'Wear and tear of the joint or inflammatory conditions can lead to stiffness and reduced mobility.' },
    ],
    treatmentApproach: 'At Remarkable Physiotherapy in Markham, care begins with a detailed assessment of your wrist, movement patterns, and daily activities. This helps identify what is contributing to your discomfort.',
    treatmentDetails: [
      { title: 'Targeted Exercise Programs', description: 'Specific exercises are used to improve mobility, strengthen supporting muscles, and restore normal movement.' },
      { title: 'Hands-On Therapy', description: 'Manual techniques can help reduce stiffness, improve joint function, and ease tension in surrounding tissues.' },
      { title: 'Activity Modification Advice', description: 'Small adjustments in how you perform daily tasks can reduce strain on your wrist and support recovery.' },
      { title: 'Posture and Ergonomic Support', description: 'Guidance on workstation setup and posture can play a key role, especially for individuals who spend long hours at a desk.' },
      { title: 'Initial Assessment', description: 'Your first session includes a detailed discussion about your symptoms, lifestyle, and goals. Physical tests help pinpoint the cause of your wrist pain.' },
      { title: 'Individual Care Plan', description: 'Based on your assessment, a structured plan is created to address your specific needs and activity level.' },
      { title: 'Ongoing Support', description: 'Progress is monitored regularly, and your program is adjusted as needed to keep you moving forward.' },
    ],
    benefits: [],
    practicalTips: [],
    practicalTipsDetails: [
      { title: 'Take Regular Breaks', description: 'If your work involves repetitive hand movements, short breaks can reduce strain.' },
      { title: 'Maintain Neutral Wrist Position', description: 'Avoid bending your wrist excessively during activities like typing or lifting.' },
      { title: 'Strengthen Forearm Muscles', description: 'Stronger muscles support the wrist and reduce the risk of injury.' },
      { title: 'Use Proper Equipment', description: 'Ergonomic keyboards, mouse devices, and supportive gear can make a noticeable difference.' },
    ],
    whyChooseUs: [
      { title: 'Focused Attention', description: 'Every session is centred on your condition, ensuring your concerns are properly addressed.' },
      { title: 'Evidence-Based Methods', description: 'The clinic uses proven techniques supported by current physiotherapy research.' },
      { title: 'Clear Communication', description: 'You will always know what is being done and why, helping you stay engaged in your recovery process.' },
      { title: 'Convenient Markham Location', description: 'Accessible services make it easier for you to stay consistent with your appointments.' },
    ],
    whenToSeekHelp: 'If your wrist pain is affecting your work, sleep, or daily routine, it’s time to take action. Early care can prevent the issue from worsening and help you return to normal activities sooner. You don’t have to let wrist pain limit your day-to-day life. Reach out to Remarkable Physiotherapy in Markham to schedule your visit. Call the clinic to book your appointment online to take the first step toward restoring comfortable wrist movement.',
  },
  {
    slug: 'headaches',
    intro: 'Headaches can interfere with work, sleep, and everyday activities. Many people in Markham deal with recurring headaches without fully knowing the cause or what options are available beyond temporary fixes. At Remarkable Physiotherapy, we focus on identifying the root factors behind your headaches and helping you move toward lasting improvement.',
    whatIsIt: 'Headaches are a common condition that can vary in intensity, frequency, and cause. They may appear as a dull ache, sharp pain, or pressure around the head, temples, or neck. Some people experience headaches occasionally, while others face them regularly, affecting their daily routine. Understanding the type of headache you are dealing with is important for proper care. Tension Headaches: These are the most common types. They often feel like a tight band around the head and may be linked to stress, poor posture, or muscle strain. Migraine Headaches: Migraines can cause intense throbbing pain, often on one side of the head. They may also include nausea, light sensitivity, and visual disturbances. Cervicogenic Headaches: These headaches originate from issues in the neck. Poor posture, stiffness, or cervical spine injury can trigger pain that radiates to the head. Cluster Headaches: These are less common but very intense. They occur in cycles and are usually felt around one eye or one side of the head.',
    symptoms: [],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Physical Factors', description: 'Muscle tension in the neck and shoulders. Poor posture, especially from prolonged sitting. Joint stiffness in the cervical spine. Previous injuries such as whiplash.' },
      { title: 'Lifestyle Factors', description: 'Stress and fatigue. Dehydration. Irregular sleep patterns. Screen overuse.' },
      { title: 'Environmental Triggers', description: 'Bright lights or loud noises. Weather changes. Strong smells.' },
    ],
    treatmentApproach: 'Physiotherapy focuses on addressing physical causes that contribute to headaches. At Remarkable Physiotherapy in Markham, care plans are based on a detailed assessment of your posture, movement patterns, and muscle function.',
    treatmentDetails: [
      { title: 'Assessment Process', description: 'Your first visit includes a thorough evaluation to determine postural alignment, neck mobility, muscle tightness or weakness, and movement habits that may contribute to headaches. This allows for a clear picture of what is causing your symptoms.' },
      { title: 'Manual Therapy', description: 'Hands-on techniques are used to improve joint movement and reduce stiffness in the neck and upper back.' },
      { title: 'Exercise Therapy', description: 'Specific exercises help strengthen weak muscles and improve posture, reducing strain on the neck.' },
      { title: 'Postural Training', description: 'Guidance on sitting, standing, and working positions can reduce recurring tension.' },
      { title: 'Soft Tissue Work', description: 'Techniques targeting tight muscles can ease pressure that contributes to headaches.' },
      { title: 'Education', description: 'You will learn how daily habits affect your condition and what adjustments can make a difference.' },
    ],
    benefits: ['Reduce how often headaches occur.', 'Improve daily comfort and focus.', 'Prevent progression into chronic patterns.', 'Support better sleep and productivity.'],
    practicalTips: [],
    practicalTipsDetails: [
      { title: 'Maintain Good Posture', description: 'Keep your head aligned over your shoulders, especially when using a computer or phone.' },
      { title: 'Take Regular Breaks', description: 'Avoid staying in one position for long periods. Short breaks can reduce muscle strain.' },
      { title: 'Stay Hydrated', description: 'Drink enough water throughout the day.' },
      { title: 'Manage Stress', description: 'Simple relaxation techniques such as deep breathing can help reduce tension.' },
      { title: 'Adjust Your Workspace', description: 'Ensure your screen is at eye level, and your chair supports your lower back.' },
    ],
    whyChooseUs: [
      { title: 'Patient-Focused Care', description: 'Each individual is carefully assessed to understand their specific situation, rather than applying a one-size-fits-all approach.' },
      { title: 'Evidence-Based Methods', description: 'Techniques used are supported by current research and clinical practice.' },
      { title: 'Focus on Root Causes', description: 'Instead of focusing solely on symptoms, attention is given to underlying issues such as posture, movement habits, and muscle imbalances.' },
      { title: 'Supportive Environment', description: 'The clinic aims to create a space where you feel comfortable discussing your concerns and progress.' },
      { title: 'Convenient Markham Location', description: 'Located in Markham, the clinic is accessible for those seeking care close to home or work.' },
    ],
    whenToSeekHelp: 'If you experience any of the following, it may be time to consult a physiotherapist: Frequent headaches. Pain that starts in the neck and spreads to the head. Headaches linked to posture or movement. Limited neck mobility. Headaches following an injury. Early assessment can help prevent the condition from becoming more persistent. Headaches don’t have to control your day. If you’re in Markham and looking for a structured approach to managing headaches, Remarkable Physiotherapy is here to assist you. Contact us today to schedule your appointment and start your path to lasting headache relief. Related Markham guide: Related reading: Chiropractic Care for Migraines in Markham. This guide explains practical education for migraines and when a Markham assessment may help. You can also book with Remarkable Physiotherapy.',
  },
  {
    slug: 'chronic-pain',
    intro: 'Living with chronic pain can affect every part of your daily life, from work and sleep to movement and mood. At Remarkable Physiotherapy in Markham, we focus on helping individuals manage chronic pain through structured care, movement-based strategies, and ongoing support. Our goal is to help you move with more ease and confidence while addressing the root causes of your condition.',
    whatIsIt: 'Chronic pain is discomfort that persists for more than 3 months, even after the initial injury or condition has healed. It can be constant or intermittent and may range from mild to severe. Unlike acute pain, which signals immediate injury, chronic pain often continues beyond normal recovery timelines. This type of pain can affect various areas of the body, including the back, neck, shoulders, hips, and joints. It may also be linked to conditions such as arthritis, nerve irritation, or past injuries that didn’t fully resolve.',
    symptoms: ['Persistent aching or stiffness', 'Burning or sharp sensations', 'Reduced mobility or flexibility', 'Muscle weakness', 'Fatigue or disrupted sleep', 'Difficulty performing daily tasks'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Previous Injuries', description: 'Injuries that were not fully rehabilitated can lead to ongoing discomfort. Scar tissue, muscle imbalance, or joint stiffness may continue to cause problems long after the initial incident.' },
      { title: 'Repetitive Strain', description: 'Repeated movements at work or during daily activities can strain muscles and joints, leading to persistent discomfort.' },
      { title: 'Nerve-Related Conditions', description: 'Nerve irritation or compression can result in ongoing pain, tingling, or numbness. Conditions such as sciatica are common examples.' },
      { title: 'Degenerative Changes', description: 'Age-related wear and tear in joints and tissues can contribute to long-term discomfort, particularly in the spine, hips, and knees.' },
    ],
    treatmentApproach: 'Physiotherapy plays a key role in managing chronic pain by addressing both physical and functional limitations. At Remarkable Physiotherapy in Markham, we use a structured approach that focuses on restoring movement and improving overall function.',
    treatmentDetails: [
      { title: 'Movement-Based Therapy', description: 'Targeted exercises help improve strength, flexibility, and coordination. These movements are selected based on your condition and gradually progress as your body adapts.' },
      { title: 'Manual Therapy', description: 'Hands-on techniques may be used to improve joint mobility, reduce stiffness, and ease muscle tension.' },
      { title: 'Posture and Movement Training', description: 'Incorrect posture and movement patterns can contribute to chronic pain. We work with you to correct these habits and reduce unnecessary strain on your body.' },
      { title: 'Education and Self-Management', description: 'You will learn practical strategies to manage your condition outside the clinic. This includes activity modification, pacing techniques, and simple exercises you can perform at home.' },
      { title: 'Initial Assessment', description: 'We evaluate your range of motion, strength, posture, and functional abilities. This allows us to identify the factors contributing to your chronic pain.' },
      { title: 'Individual Care Plan', description: 'Based on your assessment, a structured plan is created to address your needs and goals. This plan evolves as you progress.' },
      { title: 'Ongoing Support', description: 'Regular sessions help track your progress and make adjustments as needed. Our team ensures that you remain on the right path throughout your recovery journey.' },
    ],
    benefits: [],
    practicalTips: ['Stay active with gentle, regular movement.', 'Avoid prolonged sitting or inactivity.', 'Maintain proper posture during work and daily tasks.', 'Use pacing techniques to avoid overexertion.', 'Follow your prescribed exercise routine consistently.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Focus on Root Causes', description: 'We aim to identify and address the underlying factors contributing to your pain rather than just managing symptoms.' },
      { title: 'One-on-One Attention', description: 'Each session is tailored to your specific needs, ensuring you receive dedicated time and attention.' },
      { title: 'Active Approach to Recovery', description: 'We emphasize movement and functional improvement, helping you return to daily activities with greater ease.' },
      { title: 'Supportive Environment', description: 'Our clinic provides a welcoming and encouraging setting where you can feel comfortable discussing your concerns and progress.' },
    ],
    whenToSeekHelp: 'Chronic pain doesn’t have to control your life. With the right approach and consistent care, you can improve how your body feels and functions. At Remarkable Physiotherapy in Markham, we are committed to helping you move forward with confidence. Book an appointment today to learn how we can support you on your path toward improved mobility and daily comfort. Related Markham guide: Related reading: RMT for Muscle Tension in Markham: What to Expect from Registered Massage Therapy. This guide explains practical education for muscle tension and when a Markham assessment may help. You can also book with Remarkable Physiotherapy.',
  },
  {
    slug: 'shoulder-pain',
    intro: 'Shoulder pain can interfere with even the simplest daily activities, such as reaching overhead, lifting objects, or getting a full night’s sleep. Whether the discomfort started suddenly after an injury or developed gradually over time, addressing it early can make a meaningful difference. At Remarkable Physiotherapy in Markham, we focus on identifying the root cause of shoulder pain and helping you move with ease again.',
    whatIsIt: 'The shoulder is one of the most mobile joints in the body, which also makes it more prone to strain and injury. Pain can arise from muscles, tendons, ligaments, or joints within the shoulder complex.',
    symptoms: ['Difficulty lifting or rotating your arm', 'Weakness in the shoulder', 'Pain that worsens at night', 'Limited range of motion', 'Clicking, popping, or grinding sensations', 'Pain spreading down the arm or into the neck.'],
    symptomsDetails: [],
    causes: ['Rotator cuff strain or tear', 'Frozen shoulder (stiffness and reduced mobility)', 'Shoulder impingement', 'Tendon irritation or inflammation', 'Joint instability or dislocation', 'Arthritis affecting the shoulder joint', 'Poor posture or repetitive overhead movements'],
    causesDetails: [],
    treatmentApproach: 'Physiotherapy focuses on restoring movement, improving strength, and reducing strain on the affected area. At Remarkable Physiotherapy, the process begins with a detailed assessment to understand your condition and lifestyle factors.',
    treatmentDetails: [
      { title: '1. Assessment and Diagnosis', description: 'A thorough evaluation helps identify the structures involved and the severity of the issue. This step ensures that the approach aligns with your condition.' },
      { title: '2. Hands-On Techniques', description: 'Manual techniques may be used to improve joint movement and reduce stiffness in surrounding tissues.' },
      { title: '3. Targeted Exercises', description: 'Specific exercises help strengthen muscles around the shoulder, improving stability and function over time.' },
      { title: '4. Posture and Movement Correction', description: 'Daily habits, including posture and repetitive movements, often contribute to shoulder issues. Addressing these can reduce strain and support recovery.' },
      { title: '5. Education for Daily Activities', description: 'You’ll learn how to move safely during work, sports, and daily routines to avoid further irritation.' },
      { title: 'Conditions We Treat', description: 'Rotator cuff injuries. Frozen shoulder. Shoulder impingement syndrome. Tendon irritation. Post-surgical shoulder recovery. Sports-related shoulder injuries. Our approach focuses on helping you regain movement and return to your regular activities with confidence.' },
    ],
    benefits: [],
    practicalTips: ['Maintain proper posture, especially during desk work.', 'Warm up before physical activity.', 'Strengthen shoulder and upper back muscles regularly.', 'Avoid repetitive strain without breaks.', 'Use correct techniques when lifting or exercising.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'One-on-One Attention', description: 'Each session is focused on you, ensuring that your progress is monitored closely and adjustments are made when needed.' },
      { title: 'Clear Communication', description: 'We explain your condition and the steps involved in your care so you always know what to expect.' },
      { title: 'Modern Techniques', description: 'We use up-to-date methods that focus on restoring movement and reducing strain on the shoulder.' },
      { title: 'Focus on Function', description: 'The goal is not just to reduce discomfort but to help you return to your normal activities safely and confidently.' },
      { title: 'Convenient Markham Location', description: 'Our clinic is easily accessible, making it simple to attend sessions consistently.' },
    ],
    whenToSeekHelp: 'If your shoulder pain is affecting your daily routine, limiting movement, or not improving with rest, it’s time to seek professional care. Early attention can prevent minor issues from becoming more complex. Shoulder pain doesn’t have to control your day. At Remarkable Physiotherapy in Markham, we are here to help you move comfortably and confidently again. Contact us today to schedule your appointment and take the first step toward restoring your shoulder movement.',
  },
  {
    slug: 'balance-disorder',
    intro: 'Balance plays a vital role in everyday life, from simple movements like walking to more complex activities such as exercising or climbing stairs. When balance is affected, even routine tasks can become challenging. At Remarkable Physiotherapy in Markham, we focus on helping individuals manage balance disorder concerns through structured care and focused rehabilitation methods.',
    whatIsIt: 'A balance disorder refers to a condition that makes you feel unsteady, dizzy, or as if the room is spinning. It can interfere with coordination and increase the risk of falls. These issues may arise from problems in the inner ear, brain, muscles, or joints. Living with a balance disorder can impact more than just physical movement. Many individuals become cautious about walking, exercising, or even standing for long periods. This can reduce activity levels and affect overall well-being. Without proper attention, balance issues may lead to: Increased risk of falls and injuries. Reduced mobility. Difficulty performing daily tasks. Loss of confidence in movement. Addressing these concerns early can help maintain mobility and independence in daily activities.',
    symptoms: ['Dizziness or vertigo', 'Unsteadiness while standing or walking', 'Blurred vision during movement', 'Lightheadedness or faintness', 'Difficulty maintaining posture'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Inner Ear Conditions', description: 'The inner ear plays a key role in maintaining balance. Conditions such as vestibular dysfunction or infections can disrupt signals sent to the brain.' },
      { title: 'Head Injuries', description: 'Trauma to the head may affect the vestibular system, leading to coordination issues and dizziness.' },
      { title: 'Aging', description: 'As the body ages, changes in vision, muscle strength, and joint mobility can contribute to instability.' },
      { title: 'Neurological Conditions', description: 'Certain conditions affecting the brain and nervous system may interfere with coordination and spatial awareness.' },
      { title: 'Muscle Weakness and Joint Issues', description: 'Weak muscles or stiff joints can limit the body’s ability to respond to changes in position, increasing the likelihood of imbalance.' },
    ],
    treatmentApproach: 'At Remarkable Physiotherapy in Markham, the first step involves a detailed assessment to understand your condition. This includes reviewing your medical history, evaluating movement patterns, and identifying factors contributing to instability.',
    treatmentDetails: [
      { title: 'What to Expect During Assessment', description: 'Evaluation of posture and walking patterns. Testing of coordination and joint movement. Vestibular function checks. Strength and flexibility analysis. This process helps create a clear picture of your condition and guides the next steps in care.' },
      { title: 'Vestibular Rehabilitation', description: 'This approach targets the inner ear system through specific exercises that help the brain adapt to balance-related signals.' },
      { title: 'Strength and Stability Training', description: 'Improving muscle strength, particularly in the legs and core, supports better control during movement.' },
      { title: 'Coordination Exercises', description: 'Activities designed to improve body awareness and reaction time help enhance overall stability.' },
      { title: 'Gait Training', description: 'Focused walking exercises aim to improve posture, stride, and confidence while moving.' },
      { title: 'Flexibility Work', description: 'Improving joint mobility allows smoother movement and reduces stiffness that may affect balance. Each program is adjusted based on individual needs and progress, ensuring a safe and steady improvement path.' },
    ],
    benefits: [],
    practicalTips: ['Experience repeated episodes of dizziness.', 'Feel unsteady on your feet.', 'Have had recent falls or near-falls.', 'Notice difficulty with coordination.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Experienced Team', description: 'Our physiotherapists have extensive knowledge in managing balance-related conditions and use proven techniques to support recovery.' },
      { title: 'Individual Attention', description: 'Every patient receives focused care based on their specific condition and goals.' },
      { title: 'Modern Techniques', description: 'We use up-to-date methods and equipment to support effective rehabilitation.' },
      { title: 'Supportive Environment', description: 'Our clinic provides a welcoming space where patients feel comfortable working toward improved mobility.' },
      { title: 'Focus on Functional Movement', description: 'We aim to help you return to everyday activities with improved confidence and control.' },
    ],
    whenToSeekHelp: 'If you frequently feel dizzy, unsteady, or unsure while walking, it may be time to consult a physiotherapist. Early intervention can help prevent complications and improve overall movement. Living with a balance disorder can be frustrating, but support is available. At Remarkable Physiotherapy in Markham, we are committed to helping you move with greater stability and confidence. If you are experiencing symptoms of a balance disorder, now is the time to take action. Contact our clinic today to schedule an appointment and begin your path toward improved movement and control.',
  },
  {
    slug: 'fibromyalgia-treatment',
    intro: 'Fibromyalgia is a complex condition that affects how the body processes pain signals, leading to widespread discomfort, fatigue, and sensitivity. Many people in Markham live with fibromyalgia without fully understanding what is happening in their bodies or where to seek support. At Remarkable Physiotherapy, we focus on helping individuals manage symptoms, improve daily function, and regain control over their routines.',
    whatIsIt: 'Fibromyalgia is a long-term condition characterized by widespread musculoskeletal pain, along with symptoms such as fatigue, sleep disturbances, and cognitive challenges often referred to as “fibro fog.” It does not cause damage to joints or tissues, but it can significantly affect the quality of life. This condition is believed to be linked to how the brain and nervous system interpret pain signals. People with fibromyalgia may experience heightened sensitivity, meaning even mild pressure or movement can feel uncomfortable.',
    symptoms: ['Widespread body pain', 'Persistent fatigue', 'Sleep disturbances', 'Stiffness, especially in the morning', 'Difficulty concentrating', 'Headaches', 'Sensitivity to temperature, light, or noise'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Nervous System Sensitivity', description: 'People with fibromyalgia often have an amplified response to pain signals, meaning the brain processes sensations differently.' },
      { title: 'Physical or Emotional Stress', description: 'Injuries, infections, or emotional stress can sometimes trigger the onset of symptoms.' },
      { title: 'Genetics', description: 'Fibromyalgia may run in families, suggesting a genetic component.' },
      { title: 'Lifestyle Factors', description: 'Lack of physical activity, poor sleep habits, and ongoing stress can worsen symptoms over time.' },
    ],
    treatmentApproach: 'While fibromyalgia cannot be cured, physiotherapy plays an important role in managing symptoms and improving daily life. At Remarkable Physiotherapy in Markham, care focuses on reducing discomfort, improving mobility, and gradually building strength.',
    treatmentDetails: [
      { title: 'Movement-Based Therapy', description: 'Gentle, structured movement is one of the most effective ways to manage fibromyalgia. A physiotherapist will guide you through exercises that improve flexibility, strength, and endurance without overloading the body.' },
      { title: 'Pain Management Techniques', description: 'Hands-on therapy and other physical approaches can help reduce muscle tension and improve circulation. These methods aim to ease discomfort and improve movement.' },
      { title: 'Education and Self-Management', description: 'Learning how to manage fibromyalgia is key. Patients are taught pacing strategies, posture awareness, and ways to prevent flare-ups during daily activities.' },
      { title: 'Improving Sleep and Energy Levels', description: 'Better movement patterns and reduced discomfort can improve sleep, which plays a crucial role in managing fatigue associated with fibromyalgia.' },
      { title: 'Individual Assessment', description: 'Your physiotherapist will evaluate your movement, strength, and areas of discomfort to understand how fibromyalgia is affecting your body.' },
      { title: 'Structured Care Plan', description: 'A plan will be created based on your needs and tolerance levels. The focus is on gradual progress to avoid triggering symptom flare-ups.' },
      { title: 'Ongoing Support', description: 'Regular sessions help track progress and adjust your plan as needed. You will also receive exercises and strategies to continue at home.' },
    ],
    benefits: [],
    practicalTips: [],
    practicalTipsDetails: [
      { title: 'Stay Active', description: 'Low-impact activities such as walking, stretching, or swimming can help maintain mobility and reduce stiffness.' },
      { title: 'Maintain a Routine', description: 'Consistent sleep and activity schedules can support better energy levels.' },
      { title: 'Manage Stress', description: 'Relaxation techniques such as deep breathing or mindfulness can help reduce symptom flare-ups.' },
      { title: 'Listen to Your Body', description: 'Avoid overexertion. Balancing activity and rest is essential for managing fibromyalgia.' },
    ],
    whyChooseUs: [
      { title: 'Patient-Centred Approach', description: 'Every individual experiences fibromyalgia differently. The care you receive is based on your specific symptoms, goals, and comfort levels.' },
      { title: 'Focus on Sustainable Progress', description: 'Rather than pushing too hard too quickly, the emphasis is on steady improvement. This helps reduce the risk of setbacks and builds confidence over time.' },
      { title: 'Supportive Environment', description: 'Living with fibromyalgia can be challenging both physically and mentally. A supportive setting ensures you feel heard and understood throughout your care.' },
      { title: 'Practical Strategies for Daily Life', description: 'Beyond in-clinic sessions, you will learn techniques that can be applied at home, at work, and during everyday activities.' },
    ],
    whenToSeekHelp: 'Living with fibromyalgia can feel overwhelming, but you don’t have to navigate it alone. With the right approach and consistent care, you can improve how your body feels and functions. If you are in Markham and looking for support with fibromyalgia, contact Remarkable Physiotherapy today. Book an appointment to start your journey toward improved comfort, mobility, and confidence in your daily life.',
  },
];

async function run() {
  await connectDB();
  let updated = 0;
  for (const d of DETAILS) {
    const { slug, ...fields } = d;
    const res = await Condition.updateOne({ slug }, { $set: fields });
    if (res.matchedCount) updated++;
    else console.log('No condition found for slug:', slug);
  }
  console.log(`Updated exact detail content for ${updated}/${DETAILS.length} conditions`);
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
