// Verbatim condition detail content, batch 2, transcribed exactly as provided.
require('dotenv').config();
const connectDB = require('../config/db');
const Condition = require('../models/Condition');

const DETAILS = [
  {
    slug: 'hip-pain',
    intro: 'Hip pain can affect how you walk, sit, or even sleep. Whether it starts suddenly or develops over time, it can interfere with everyday life and limit movement. At Remarkable Physiotherapy in Markham, we focus on identifying the source of hip pain and helping you move with comfort and confidence again.',
    whatIsIt: 'The hip joint is one of the largest joints in the body. It supports body weight and allows smooth movement in multiple directions. Hip pain may be felt in the groin, outer thigh, buttock, or may even radiate down the leg. It can result from joint issues, muscle strain, or problems with surrounding soft tissues. Some people experience hip pain during activity, while others notice stiffness after long periods of sitting or resting.',
    symptoms: [],
    symptomsDetails: [
      { title: 'Persistent Discomfort', description: 'Pain that lasts more than a few days or keeps returning may indicate an underlying issue.' },
      { title: 'Limited Range of Motion', description: 'Difficulty in bending, walking, or rotating the hip can signal joint or muscle involvement.' },
      { title: 'Swelling or Tenderness', description: 'Visible swelling or sensitivity around the hip may indicate inflammation.' },
      { title: 'Pain During Movement', description: 'Discomfort while walking, climbing stairs, or standing from a seated position should not be overlooked.' },
    ],
    causes: [],
    causesDetails: [
      { title: 'Muscle and Tendon Strain', description: 'Overuse, sudden movement, or improper posture can strain the muscles and tendons around the hip. This is common among active individuals and those with physically demanding routines.' },
      { title: 'Arthritis', description: 'Wear and tear in the hip joint can lead to stiffness, swelling, and reduced mobility. This is more common with age, but it can affect younger individuals as well.' },
      { title: 'Bursitis', description: 'Small fluid-filled sacs called bursae reduce friction in the joint. When they become inflamed, it can cause sharp or aching pain on the outside of the hip.' },
      { title: 'Labral Tears', description: 'The labrum is a ring of cartilage that supports the hip joint. Tears can cause clicking sensations, instability, or deep joint discomfort.' },
      { title: 'Referred Pain', description: 'Sometimes the issue may not originate in the hip itself. Lower back conditions or nerve irritation can send pain signals to the hip area.' },
    ],
    treatmentApproach: 'Physiotherapy plays a key role in addressing both the symptoms and underlying causes of hip pain. It helps restore movement, improve strength, and reduce strain on the joint. With consistent care, many people notice improved mobility and greater ease during daily activities.',
    treatmentDetails: [
      { title: 'Detailed Physical Assessment', description: 'We evaluate your posture, movement patterns, joint mobility, and muscle strength to understand the root cause.' },
      { title: 'Movement Analysis', description: 'Observing how you walk, sit, and perform daily activities helps identify imbalances or stress points.' },
      { title: 'Goal-Based Planning', description: 'Your daily routine, activity level, and personal goals are taken into account when outlining your care plan.' },
      { title: 'Manual Therapy', description: 'Hands-on techniques are used to improve joint mobility and reduce stiffness in the hip region.' },
      { title: 'Exercise Programs', description: 'Targeted exercises help strengthen muscles, improve flexibility, and support proper joint function.' },
      { title: 'Posture and Movement Training', description: 'We guide you on how to sit, stand, and move in ways that reduce stress on your hip.' },
      { title: 'Soft Tissue Work', description: 'Techniques focused on muscles and connective tissues can help ease tightness and improve circulation.' },
      { title: 'Gradual Activity Progression', description: 'You are guided through a step-by-step increase in activity to ensure safe and steady improvement.' },
    ],
    benefits: [],
    practicalTips: [],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Focused Attention', description: 'Each session is structured around your specific condition, ensuring that your progress is carefully monitored.' },
      { title: 'Evidence-Based Methods', description: 'All techniques and exercises are based on proven approaches used in modern physiotherapy practice.' },
      { title: 'Clear Communication', description: 'You are informed about your condition, what to expect, and how each step contributes to your progress.' },
      { title: 'Support Beyond the Clinic', description: 'You receive guidance on exercises and habits to follow at home, helping maintain progress between sessions.' },
      { title: 'Convenient Markham Location', description: 'Our clinic is easily accessible, making it simple to attend appointments and stay consistent with your care.' },
    ],
    whenToSeekHelp: 'If hip pain is affecting your ability to move freely, disrupting your daily routine, or getting worse over time, it is time to take action. Early attention can prevent further complications and help restore function more efficiently. If you are dealing with hip pain in Markham, Remarkable Physiotherapy is here to help you move forward with confidence. Book an appointment today at our clinic to speak with our team. Taking that first step can make a meaningful difference in how you feel and move each day.',
  },
  {
    slug: 'neck-pain',
    intro: 'Neck pain is a common issue that can affect daily activities, work performance, and overall comfort. Whether it develops from long hours at a desk, poor posture, an injury, or stress, it can gradually limit movement and make even simple tasks difficult. At Remarkable Physiotherapy in Markham, our focus is on identifying the root cause of neck pain and helping you restore movement, strength, and function through proven methods.',
    whatIsIt: 'Neck pain refers to discomfort or stiffness in the cervical spine, which supports the head and allows a wide range of motion. When muscles, joints, or nerves in this area are affected, symptoms can range from mild stiffness to persistent discomfort. Neck pain can go beyond physical discomfort. It may interfere with concentration, sleep quality, and productivity. Simple actions, such as turning your head while driving or working on a computer, can become challenging. Over time, this can impact both personal and professional life.',
    symptoms: ['Stiffness or reduced range of motion', 'Sharp or dull aches in the neck', 'Headaches, especially starting from the base of the skull', 'Pain that spreads to the shoulders or arms', 'Muscle tightness or spasms', 'Tingling or numbness in severe cases'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Poor Posture', description: 'Spending long hours looking down at phones or sitting at a desk can strain the neck. This is often called “tech neck” and is increasingly common.' },
      { title: 'Muscle Strain', description: 'Overuse, sudden movements, or sleeping in an awkward position can strain neck muscles, leading to discomfort.' },
      { title: 'Injury or Trauma', description: 'Whiplash from car accidents or sports injuries can damage soft tissues and joints in the neck.' },
      { title: 'Degenerative Conditions', description: 'Age-related changes, such as disc wear or joint changes, can lead to stiffness and ongoing discomfort.' },
      { title: 'Stress and Tension', description: 'Emotional stress can cause neck and shoulder muscles to tighten, contributing to ongoing discomfort.' },
    ],
    treatmentApproach: 'At Remarkable Physiotherapy in Markham, we take a structured approach to assess and address neck pain. Each session focuses on improving mobility, reducing strain, and restoring normal function.',
    treatmentDetails: [
      { title: 'Initial Assessment', description: 'We begin with a detailed evaluation to identify the source of your neck pain. This includes posture analysis, movement testing, and a review of your daily habits.' },
      { title: 'Hands-On Therapy', description: 'Manual techniques are used to improve joint mobility and reduce muscle tension. This helps restore natural movement in the neck.' },
      { title: 'Exercise Programs', description: 'Targeted exercises are introduced to strengthen supporting muscles and improve flexibility. These exercises also help prevent future issues.' },
      { title: 'Postural Correction', description: 'We guide you on proper posture during daily activities such as sitting, working, and using devices.' },
      { title: 'Education and Prevention', description: 'You will learn practical strategies to manage your condition and avoid triggers that may lead to recurring pain.' },
    ],
    benefits: ['Improved range of motion', 'Reduced stiffness and tension', 'Stronger supporting muscles', 'Improved posture', 'Reduced risk of recurring issues'],
    practicalTips: [],
    practicalTipsDetails: [
      { title: 'Maintain Proper Posture', description: 'Keep your screen at eye level and avoid slouching.' },
      { title: 'Take Regular Breaks', description: 'If you sit for long periods, take short breaks to stretch and move.' },
      { title: 'Use Proper Support While Sleeping', description: 'Choose a pillow that keeps your neck in a neutral position.' },
      { title: 'Stay Active', description: 'Gentle movement and stretching can help prevent stiffness.' },
    ],
    whyChooseUs: [
      { title: 'One-on-One Care', description: 'Each session is focused on your condition, ensuring you receive proper attention throughout your visit.' },
      { title: 'Goal-Oriented Plans', description: 'Your progress is tracked, and your program is adjusted as you improve.' },
      { title: 'Modern Techniques', description: 'We use up-to-date methods that focus on movement, strength, and function.' },
      { title: 'Supportive Environment', description: 'Our team is committed to helping you stay on track and motivated during your recovery.' },
    ],
    whenToSeekHelp: 'If your neck pain lasts more than a few days, keeps returning, or begins to affect your daily routine, it’s time to seek professional care. Early attention can prevent the condition from becoming more serious. If you are dealing with neck pain in Markham, Remarkable Physiotherapy is here to help you move comfortably again. Our team is ready to assess your condition and guide you through a structured plan. Contact us today to book your appointment and take the first step toward improved neck mobility and daily comfort. Related Markham guide: Related reading: Neck Pain & Tech Neck: A Markham Physiotherapy Guide. This guide explains practical education for neck pain and when a Markham assessment may help. You can also book with Remarkable Physiotherapy. Related Markham guide: Related reading: Chiropractic Care for Tech Neck and Desk-Related Stiffness in Markham. This guide explains practical education for neck stiffness and when a Markham assessment may help. You can also book with Remarkable Physiotherapy.',
  },
  {
    slug: 'hand-pain',
    intro: 'Hand pain can make even simple daily tasks feel difficult. From typing and writing to lifting objects or gripping tools, discomfort in the hands can interfere with work, hobbies, and routine activities. At Remarkable Physiotherapy in Markham, we focus on identifying the root cause of hand pain and helping you restore movement, strength, and function.',
    whatIsIt: 'Hand pain refers to discomfort or soreness in any part of the hand, including the fingers, palm, or wrist. It may develop suddenly due to an injury or gradually over time from repeated use. The hands are made up of small bones, joints, muscles, tendons, and nerves, all of which work together. When one or more of these structures is affected, pain can occur.',
    symptoms: ['Aching or sharp pain in the fingers, palm, or wrist', 'Swelling or stiffness', 'Difficulty gripping or holding objects', 'Tingling or numbness', 'Reduced range of motion', 'Weakness in the hand or fingers'],
    symptomsDetails: [],
    causes: ['Repetitive strain injuries from typing, using tools, or prolonged phone use', 'Carpal tunnel syndrome, where pressure on a nerve leads to tingling and discomfort', 'Arthritis, which causes joint stiffness and swelling', 'Tendonitis, resulting from overuse of tendons.', 'Sprains and fractures due to falls or accidents', 'Nerve-related issues causing numbness or weakness'],
    causesDetails: [],
    treatmentApproach: 'Physiotherapy plays an important role in managing hand pain. At Remarkable Physiotherapy in Markham, the focus is on improving function and addressing the underlying cause rather than just the symptoms.',
    treatmentDetails: [
      { title: 'Thorough Assessment', description: 'Your care begins with a detailed evaluation. This includes reviewing your medical history, daily activities, and the specific movements that trigger discomfort. By identifying the root issue, a focused plan can be created.' },
      { title: 'Targeted Treatment Methods', description: 'Manual therapy to improve joint and soft tissue movement. Exercise programs to strengthen muscles and support joints. Stretching routines to increase flexibility. Education on posture and ergonomics to reduce strain during daily tasks. Activity modification advice to prevent further irritation.' },
      { title: 'Gradual Recovery Process', description: 'Recovery is a step-by-step process. With consistent care and the right approach, many individuals notice improved mobility, reduced discomfort, and stronger hand function over time.' },
      { title: 'Carpal Tunnel Syndrome', description: 'This condition occurs when the median nerve is compressed at the wrist. It often causes tingling, numbness, and weakness in the hand. Early care can help prevent worsening symptoms.' },
      { title: 'Tendon Injuries', description: 'Overuse or strain can irritate the tendons in the hand and wrist. This can lead to pain during movement and reduced strength.' },
      { title: 'Arthritis in the Hand', description: 'Joint wear and tear can result in stiffness and swelling, making movement difficult. Physiotherapy can help maintain mobility and function.' },
      { title: 'Post-Injury Rehabilitation', description: 'After fractures, sprains, or surgeries, structured rehabilitation is essential for restoring normal hand use.' },
    ],
    benefits: [],
    practicalTips: ['Take regular breaks from repetitive tasks.', 'Maintain proper wrist and hand positioning while working.', 'Use ergonomic tools when possible.', 'Perform gentle stretching exercises.', 'Avoid overloading the hand during recovery.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Individual Attention', description: 'Each person’s condition is different. Time is taken to understand your concerns and develop a plan that suits your needs and daily routine.' },
      { title: 'Focus on Function', description: 'The aim is not just to reduce discomfort but to help you return to your normal activities with confidence and ease.' },
      { title: 'Evidence-Based Care', description: 'Treatment methods are based on current research and clinical knowledge to ensure safe and effective care.' },
      { title: 'Support Throughout Your Journey', description: 'You are guided through each stage of your recovery, with adjustments made as you progress.' },
    ],
    whenToSeekHelp: 'If your hand pain lasts more than a few days, interferes with daily activities, or is accompanied by numbness or weakness, it is time to seek professional care. Early attention can prevent the condition from worsening. Hand pain should not hold you back from your daily life. At Remarkable Physiotherapy in Markham, we are here to help you move comfortably and confidently again. Contact us today to schedule your appointment and take the first step toward restoring your hand function.',
  },
  {
    slug: 'elbow-pain',
    intro: 'Elbow pain can make everyday movements like lifting, gripping, or even typing feel difficult. Whether it develops gradually or appears suddenly after an activity, this condition can interfere with work, sports, and daily routines. At Remarkable Physiotherapy in Markham, we focus on identifying the source of elbow pain and helping you return to normal movement with confidence.',
    whatIsIt: 'Elbow pain refers to discomfort around the joint where the upper arm meets the forearm. This joint plays a key role in bending, straightening, and rotating the arm. Pain can arise from muscles, tendons, ligaments, or joint structures, depending on the underlying issue. Even mild elbow pain can disrupt your routine. Tasks such as carrying groceries, working on a computer, or participating in sports can become challenging. Without proper attention, the condition may progress, making recovery more difficult. At Remarkable Physiotherapy in Markham, the goal is to help you regain strength, flexibility, and control in your arm so you can return to your usual activities without discomfort.',
    symptoms: ['Pain when gripping objects or shaking hands', 'Stiffness or reduced movement in the elbow', 'Tenderness around the joint', 'Weakness in the forearm or wrist', 'Tingling or numbness radiating down the arm'],
    symptomsDetails: [],
    causes: ['Tennis elbow (lateral epicondylitis): Often caused by repetitive wrist and arm motions', 'Golfer’s elbow (medial epicondylitis): Linked to strain on the inner side of the elbow', 'Overuse injuries: Repetitive tasks such as typing, lifting, or manual work', 'Sports-related strain: Activities like tennis, golf, or weightlifting', 'Joint stiffness or inflammation: May occur due to age, injury, or underlying conditions', 'Nerve irritation: Can lead to tingling or weakness in the arm'],
    causesDetails: [],
    treatmentApproach: 'We take a structured and practical approach to managing elbow pain. Every individual is different, so care begins with a detailed assessment to determine the root cause of your symptoms.',
    treatmentDetails: [
      { title: 'Thorough Assessment', description: 'Your first visit includes a physical evaluation of your elbow, wrist, and shoulder. This helps identify movement limitations, muscle imbalances, and areas of strain.' },
      { title: 'Targeted Therapy Techniques', description: 'Manual therapy to improve joint and soft tissue movement. Stretching techniques to reduce tension. Strength-building exercises to support the elbow. Activity modification to prevent further strain.' },
      { title: 'Progressive Exercise Plans', description: 'Exercises play a key role in recovery. You will receive a structured plan designed to improve mobility and gradually rebuild strength. These exercises can also help reduce the risk of recurring elbow pain.' },
      { title: 'Tennis Elbow', description: 'Often seen in individuals who perform repetitive arm movements, this condition causes pain on the outer part of the elbow. It can affect athletes and people with desk jobs.' },
      { title: 'Golfer’s Elbow', description: 'This condition affects the inner elbow and is commonly associated with repetitive gripping or wrist flexion activities.' },
      { title: 'Tendon Strain', description: 'Overuse or sudden stress can cause irritation of the tendons surrounding the elbow joint.' },
      { title: 'Post-Injury Rehabilitation', description: 'If you’ve experienced a fall, accident, or sports injury, structured rehabilitation can support a safe return to activity.' },
    ],
    benefits: [],
    practicalTips: ['Take breaks during repetitive tasks.', 'Use proper technique during sports or lifting.', 'Maintain strength and flexibility in the arm.', 'Avoid sudden increases in activity intensity.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Individual Attention', description: 'Each session is focused on your condition, ensuring that your progress is monitored and adjusted as needed.' },
      { title: 'Evidence-Based Methods', description: 'Our approach is grounded in proven physiotherapy techniques that aim to improve movement and reduce discomfort.' },
      { title: 'Focus on Functional Recovery', description: 'We emphasize restoring your ability to perform daily tasks and activities that matter most to you.' },
      { title: 'Supportive Environment', description: 'Our team is committed to creating a space where you feel comfortable and confident throughout your care journey.' },
    ],
    whenToSeekHelp: 'If your elbow pain lasts more than a few days, limits your movement, or interferes with your routine, it’s time to seek professional care. Early attention can make a significant difference in recovery time and overall function. If you’re dealing with elbow pain in Markham, Remarkable Physiotherapy is here to help you move forward with confidence. Our team is ready to assess your condition and create a plan that supports your recovery. Contact us today to schedule your appointment or speak with our team about your concerns. Taking the first step now can help you get back to your daily activities with greater ease.',
  },
  {
    slug: 'sciatica-pain',
    intro: 'Sciatica pain can disrupt daily life, making even simple movements uncomfortable. At Remarkable Physiotherapy in Markham, we focus on identifying the root cause of your discomfort and helping you move with ease again. If you’re dealing with sharp, radiating pain from your lower back down your leg, you’re not alone, and there are ways to manage it effectively.',
    whatIsIt: 'Sciatica refers to irritation or compression of the sciatic nerve, the longest nerve in the body. It runs from your lower back through your hips and down each leg. When this nerve is affected, it can lead to symptoms that vary in intensity and duration. Living with sciatica pain can make simple tasks challenging. Sitting for long hours, standing, or even walking short distances may trigger discomfort. Sleep can also be affected, leading to fatigue and reduced productivity. If left unaddressed, symptoms may persist or worsen over time. That’s why early attention and proper care are important for recovery.',
    symptoms: ['Sharp or shooting pain in the lower back, buttocks, or leg', 'Tingling or “pins and needles” sensation', 'Numbness along the nerve pathway', 'Weakness in the affected leg', 'Pain that worsens with sitting or sudden movements'],
    symptomsDetails: [],
    causes: ['Herniated or slipped discs', 'Spinal stenosis (narrowing of the spinal canal)', 'Degenerative disc changes', 'Muscle tightness, especially in the piriformis', 'Poor posture or prolonged sitting', 'Injury or trauma'],
    causesDetails: [],
    treatmentApproach: 'At Remarkable Physiotherapy in Markham, we take a structured approach to managing sciatica pain. The goal is to reduce discomfort, restore movement, and prevent recurrence.',
    treatmentDetails: [
      { title: 'Initial Assessment', description: 'Your visit begins with a detailed evaluation to understand your symptoms, posture, movement patterns, and medical history. This helps identify the source of nerve irritation.' },
      { title: '1. Manual Therapy', description: 'Hands-on techniques improve joint mobility and reduce muscle tension, helping ease pressure on the sciatic nerve.' },
      { title: '2. Exercise Programs', description: 'Targeted exercises help strengthen the muscles supporting your spine, improve flexibility, and promote proper alignment.' },
      { title: '3. Postural Training', description: 'Many cases of sciatica are linked to posture. We guide you on sitting, standing, and movement habits that reduce strain on your lower back.' },
      { title: '4. Soft Tissue Techniques', description: 'These techniques focus on releasing tight muscles that may be contributing to nerve compression.' },
      { title: '5. Education and Lifestyle Advice', description: 'You’ll learn how to manage symptoms at home, avoid triggers, and maintain progress over time.' },
    ],
    benefits: ['Reduced nerve irritation', 'Improved flexibility and strength', 'Better posture and movement patterns', 'Increased comfort during daily activities', 'Lower risk of recurring pain'],
    practicalTips: ['Maintain proper posture while sitting and standing.', 'Take breaks if you sit for long periods.', 'Stay active with regular stretching and strengthening exercises.', 'Use proper techniques when lifting heavy objects.', 'Keep a healthy body weight to reduce spinal strain.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Individual-Focused Care', description: 'Each person’s condition is different. We take time to understand your specific situation and plan accordingly.' },
      { title: 'Experienced Team', description: 'Our physiotherapists have extensive experience treating musculoskeletal conditions, including sciatica.' },
      { title: 'Modern Techniques', description: 'We use up-to-date methods and approaches supported by current physiotherapy research.' },
      { title: 'Supportive Environment', description: 'You’ll receive clear explanations, guidance, and encouragement throughout your visits.' },
      { title: 'Convenient Markham Location', description: 'An easily accessible clinic location makes it simple to stay consistent with your sessions.' },
    ],
    whenToSeekHelp: 'If you notice persistent pain, numbness, or weakness that doesn’t improve within a few days, it’s time to seek professional care. Early attention can prevent the condition from becoming more severe. Sciatica pain doesn’t have to control your routine. With the right approach, you can move more comfortably and return to the activities you enjoy. If you’re in Markham and dealing with sciatica pain, the team at Remarkable Physiotherapy is here to help. Book your appointment today to learn more about how we can support your recovery.',
  },
  {
    slug: 'gait-disorders',
    intro: 'Walking is something most people take for granted until it becomes difficult. Gait disorders can affect how you move, balance, and carry out everyday activities. At Remarkable Physiotherapy in Markham, we focus on identifying the root causes of gait disorders and helping individuals restore smoother, safer movement patterns.',
    whatIsIt: 'Gait disorders refer to abnormalities in the way a person walks. These changes can involve speed, rhythm, balance, or coordination. Some individuals may notice limping, shuffling, or difficulty maintaining stability while walking. These conditions can develop gradually or appear suddenly, depending on the underlying cause. Regardless of how they begin, gait issues can impact mobility, independence in daily tasks, and overall quality of life. Reduced Mobility: Walking difficulties can limit your ability to move around freely, whether at home, work, or outdoors. Increased Risk of Falls: Impaired balance and coordination raise the likelihood of falls, which can lead to serious injuries. Impact on Confidence: Struggling with walking can lead to hesitation in social or physical activities, affecting overall well-being.',
    symptoms: ['Uneven or unsteady walking', 'Dragging of the feet', 'Shortened steps', 'Difficulty starting or stopping movement', 'Frequent falls or near-falls', 'Pain while walking'],
    symptomsDetails: [],
    causes: [],
    causesDetails: [
      { title: 'Neurological Conditions', description: 'Disorders affecting the brain or nervous system often influence walking patterns. Conditions such as stroke, Parkinson’s disease, or multiple sclerosis can interfere with coordination and muscle control.' },
      { title: 'Musculoskeletal Issues', description: 'Joint stiffness, muscle weakness, or injuries can alter how the body moves. Hip, knee, or ankle problems frequently contribute to abnormal gait patterns.' },
      { title: 'Balance and Vestibular Problems', description: 'Inner ear dysfunction can disrupt balance, leading to unsteady walking or frequent falls.' },
      { title: 'Age-Related Changes', description: 'As people age, changes in strength, flexibility, and reaction time can affect walking ability. This may result in slower movement or increased risk of tripping.' },
    ],
    treatmentApproach: 'At Remarkable Physiotherapy in Markham, the first step involves a thorough assessment. This includes analyzing your walking pattern, posture, joint mobility, and muscle strength. Addressing gait disorders early can prevent worsening symptoms and reduce the risk of complications. Early care can also improve movement efficiency and help maintain independence in daily activities.',
    treatmentDetails: [
      { title: 'Movement Analysis', description: 'We observe how your body moves during walking to identify irregular patterns and contributing factors.' },
      { title: 'Individual Condition Review', description: 'Every case is different, so we take time to understand your history, lifestyle, and specific challenges.' },
      { title: 'Exercise Programs', description: 'Targeted exercises focus on improving strength, flexibility, and coordination. These exercises are designed to support proper movement patterns.' },
      { title: 'Balance Training', description: 'Improving balance plays a key role in reducing instability. Training may include controlled movements and stability exercises.' },
      { title: 'Walking Retraining', description: 'We help correct walking patterns through guided techniques that improve step length, posture, and rhythm.' },
      { title: 'Manual Therapy', description: 'Hands-on techniques can help improve joint mobility and reduce stiffness, making walking more efficient.' },
      { title: 'Assistive Device Training', description: 'If needed, we guide you on using tools such as canes or walkers safely and effectively.' },
    ],
    benefits: [],
    practicalTips: ['Older adults experiencing balance issues.', 'Individuals recovering from injury or surgery.', 'People with neurological conditions.', 'Anyone noticing changes in walking patterns.'],
    practicalTipsDetails: [
      { title: 'Stay Active', description: 'Regular movement helps maintain muscle strength and joint mobility.' },
      { title: 'Wear Proper Footwear', description: 'Shoes with adequate support can improve stability and reduce strain.' },
      { title: 'Maintain Good Posture', description: 'Keeping your body aligned while walking can improve efficiency and reduce discomfort.' },
      { title: 'Address Pain Early', description: 'Ignoring discomfort can lead to compensatory movements that worsen gait issues.' },
    ],
    whyChooseUs: [
      { title: 'Patient-Focused Care', description: 'We take time to understand your condition and goals, ensuring your care plan aligns with your needs.' },
      { title: 'Evidence-Based Methods', description: 'Our approach is grounded in proven techniques that focus on improving mobility and function.' },
      { title: 'One-on-One Attention', description: 'You receive dedicated time with a physiotherapist who monitors your progress and adjusts your plan as needed.' },
      { title: 'Supportive Environment', description: 'We aim to create a welcoming space where you feel comfortable working toward improved movement.' },
    ],
    whenToSeekHelp: 'Gait disorders can make everyday life more challenging, but the right care can make a meaningful difference. At Remarkable Physiotherapy in Markham, we are committed to helping you move with greater ease and confidence. If you are experiencing difficulty walking or have concerns about your movement, now is the time to take action. Contact Remarkable Physiotherapy today to schedule your appointment and start your journey toward improved mobility.',
  },
  {
    slug: 'arthritis-treatment',
    intro: 'Arthritis is a common condition that affects joints, leading to stiffness, discomfort, and reduced movement. Many people in Markham face challenges in their daily routines due to arthritis, whether it’s difficulty walking, gripping objects, or staying active. At Remarkable Physiotherapy, we focus on helping individuals manage arthritis and maintain an active lifestyle through structured care and movement-based strategies.',
    whatIsIt: 'Arthritis is not a single condition but a term used to describe joint inflammation. It can affect people of all ages, though it is more common as people grow older. The condition can impact one joint or multiple joints, often causing discomfort, swelling, and limited mobility.',
    symptoms: ['Joint stiffness, especially in the morning', 'Swelling around joints', 'Reduced range of motion', 'Persistent discomfort during movement or rest', 'Weakness in the surrounding muscles'],
    symptomsDetails: [],
    causes: ['Osteoarthritis: Caused by wear and tear of joint cartilage over time', 'Rheumatoid Arthritis: An autoimmune condition where the body attacks joint tissues', 'Psoriatic Arthritis: Associated with psoriasis, affecting both skin and joints', 'Post-Traumatic Arthritis: Develops after an injury to a joint'],
    causesDetails: [
      { title: 'Causes and Risk Factors', description: 'Aging and natural joint wear. Previous injuries or repetitive strain. Genetic predisposition. Autoimmune conditions. Lifestyle habits, such as inactivity.' },
    ],
    treatmentApproach: 'At Remarkable Physiotherapy in Markham, physiotherapy plays a key role in managing arthritis. The focus is on improving joint function, maintaining mobility, and reducing discomfort through structured techniques.',
    treatmentDetails: [
      { title: 'Movement-Based Therapy', description: 'Targeted exercises help strengthen muscles around affected joints. Stronger muscles provide better support and reduce strain on joints. These exercises are carefully selected based on your condition and comfort level.' },
      { title: 'Joint Mobility Work', description: 'Gentle techniques are used to improve joint flexibility and reduce stiffness. This can make daily movements like walking, bending, or reaching much easier.' },
      { title: 'Pain Management Techniques', description: 'Various non-invasive methods are used to manage discomfort, such as manual therapy, stretching routines, and physical modalities. These approaches aim to ease joint stress and improve overall function.' },
      { title: 'Education and Lifestyle Advice', description: 'Learning how to move safely, maintain posture, and modify daily activities can make a big difference. Small changes in routine can reduce strain on joints and improve long-term joint health.' },
      { title: 'Initial Assessment', description: 'We evaluate your mobility, strength, posture, and daily activity challenges. This allows us to create a structured plan suited to your needs.' },
      { title: 'Ongoing Care Plan', description: 'Your sessions will include guided exercises, hands-on techniques, and progress tracking. The plan evolves as your condition changes, ensuring steady improvement in function.' },
      { title: 'Home Exercise Program', description: 'You will also receive exercises to perform at home. Consistency plays a major role in maintaining joint mobility and strength between sessions.' },
    ],
    benefits: [],
    practicalTips: [],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Patient-Focused Approach', description: 'Every individual is different, and care plans are adjusted based on your specific condition, goals, and comfort level.' },
      { title: 'Evidence-Based Techniques', description: 'The methods used are grounded in current research and clinical practice, ensuring safe and effective care.' },
      { title: 'Supportive Environment', description: 'Our clinic provides a welcoming and encouraging setting where you can work toward improved mobility with confidence.' },
      { title: 'Focus on Daily Function', description: 'The goal is not just to address symptoms but to help you move more freely in your everyday activities, whether that’s walking, working, or enjoying time with family.' },
    ],
    whenToSeekHelp: 'Markham’s active lifestyle can be challenging for those with arthritis, especially during colder months when stiffness may increase. Staying active, maintaining a consistent exercise routine, and seeking professional care can help manage symptoms effectively. Simple habits such as regular stretching, staying warm, and avoiding prolonged inactivity can support joint health. Combining these habits with physiotherapy care can lead to noticeable improvements in movement and comfort. If arthritis is affecting your daily life, it’s important to take action early. At Remarkable Physiotherapy in Markham, we are here to help you move with greater ease and confidence. Book an appointment today at our clinic to learn more about how we can support your arthritis care journey.',
  },
  {
    slug: 'motor-vehicle-accident-injuries',
    intro: 'Motor vehicle accident injuries can disrupt daily life in both immediate and long-lasting ways. Whether it’s a minor collision or a more serious crash, the impact on your body can lead to pain, stiffness, and reduced mobility. At Remarkable Physiotherapy in Markham, we focus on helping individuals recover from motor vehicle accident injuries with structured care that addresses both symptoms and underlying issues.',
    whatIsIt: 'Motor vehicle accident injuries refer to physical conditions that occur as a result of a car crash or similar incident. These injuries may not always be visible right away. In many cases, symptoms develop hours or even days later. Whiplash is one of the most frequently reported conditions, caused by a sudden forward and backward motion of the neck. This can lead to stiffness, discomfort, and a limited range of motion.',
    symptoms: ['Persistent neck or back pain', 'Reduced mobility or stiffness', 'Headaches or dizziness', 'Tingling or numbness in arms or legs', 'Muscle weakness', 'Difficulty performing everyday activities'],
    symptomsDetails: [],
    causes: ['Whiplash and neck strain', 'Back pain and spinal issues', 'Shoulder injuries', 'Soft tissue damage (muscles, ligaments, tendons)', 'Headaches and concussions', 'Knee and joint injuries'],
    causesDetails: [],
    treatmentApproach: 'Physiotherapy plays a key role in restoring movement, reducing discomfort, and improving overall function after a motor vehicle accident. At Remarkable Physiotherapy in Markham, care plans are structured based on individual needs and injury type.',
    treatmentDetails: [
      { title: '1. Detailed Assessment', description: 'A thorough evaluation helps identify the extent of the injury and areas that require attention. This includes posture analysis, movement testing, and pain assessment.' },
      { title: '2. Manual Therapy', description: 'Hands-on techniques are used to improve joint mobility and reduce muscle tension. This can help restore natural movement patterns.' },
      { title: '3. Exercise Programs', description: 'Specific exercises are introduced to strengthen muscles, improve flexibility, and support recovery. These exercises also help prevent future complications.' },
      { title: '4. Postural Training', description: 'Improving posture reduces strain on injured areas and supports long-term function in daily activities.' },
      { title: '5. Education and Self-Management', description: 'Patients are guided on managing symptoms at home, including movement strategies and activity modifications.' },
      { title: 'Step-by-Step Process', description: 'Initial consultation and assessment. Identification of problem areas. Development of a recovery plan. Ongoing sessions with progress tracking. Adjustments based on improvement. This structured approach ensures that your progress is monitored and your care evolves as you recover.' },
    ],
    benefits: ['Faster return to daily activities', 'Reduced risk of chronic conditions', 'Improved mobility and strength', 'Prevention of further complications'],
    practicalTips: ['Avoid sudden movements that strain injured areas.', 'Maintain proper sitting and standing posture.', 'Stay consistent with prescribed exercises.', 'Take breaks during prolonged activities.'],
    practicalTipsDetails: [],
    whyChooseUs: [
      { title: 'Patient-Focused Care', description: 'Each treatment plan is tailored to your condition, goals, and recovery timeline.' },
      { title: 'Evidence-Based Techniques', description: 'Our approach is grounded in proven methods that aim to restore function and mobility efficiently.' },
      { title: 'Supportive Environment', description: 'We prioritize clear communication so you always know what to expect throughout your recovery.' },
      { title: 'Convenient Markham Location', description: 'Located in Markham, our clinic is easily accessible for individuals seeking care after an accident.' },
    ],
    whenToSeekHelp: 'Delaying care after a motor vehicle accident can lead to prolonged discomfort and secondary issues. When injuries are not addressed early, the body may develop compensatory patterns that affect other areas. Seeking care soon after an accident ensures that even minor injuries are properly managed before they escalate. Motor vehicle accident injuries can affect your quality of life, but the right care can help you regain movement and function. At Remarkable Physiotherapy in Markham, we are committed to supporting your recovery with structured care and a clear plan. If you’ve recently been in an accident or are experiencing ongoing discomfort, now is the time to take action. Book an appointment with Remarkable Physiotherapy today to learn more about how we can assist you on your path to recovery.',
  },
];

async function run() {
  await connectDB();
  let updated = 0;
  for (const d of DETAILS) {
    const { slug, ...fields } = d;
    const res = await Condition.updateOne({ slug }, { $set: fields });
    if (res.matchedCount) updated++;
    else console.log('No condition found for slug:', slug);
  }
  console.log(`Updated exact detail content for ${updated}/${DETAILS.length} conditions`);
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
