// Local fallback content used whenever the backend API is unreachable or
// returns empty data. Keeps the site fully functional/demoable offline.

const SERVICE_IMAGES = [
  'https://images.unsplash.com/photo-1519824145371-296894a0daa9?q=80&w=1200&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1200&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1550831107-1553da8c8464?q=80&w=1200&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1200&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1600334129128-685c5582fd35?q=80&w=1200&auto=format&fit=crop',
]

export const PLACEHOLDER_SERVICES = [
  {
    name: 'Physiotherapy',
    shortDescription: 'Movement, strength and recovery support.',
    description: 'Living with discomfort, stiffness, or limited movement can affect every part of your routine. At Markham Pain Clinic, the focus is on helping you move with ease, restore strength, and return to the activities that matter to you.',
  },
  {
    name: 'Chiropractic Care',
    shortDescription: 'Spine, joint and mobility-focused care.',
    description: 'Chiropractic Care focuses on the relationship between the spine, joints, and the nervous system. When alignment issues occur, they can affect how your body moves and feels during daily activities.',
  },
  {
    name: 'Massage Therapy',
    shortDescription: 'Muscle tension and relaxation support.',
    description: 'When daily stress, muscle tension, or physical strain begin to interfere with your routine, Massage Therapy can play a valuable role in restoring balance.',
  },
  {
    name: 'Acupuncture',
    shortDescription: 'Fine-needle stimulation of selected points.',
    description: 'Acupuncture is a time-tested therapy that aims to restore balance in the body by stimulating specific points with fine needles.',
  },
  {
    name: 'Manual Therapy',
    shortDescription: 'Hands-on muscle, joint and tissue techniques.',
    description: 'Manual therapy is a hands-on approach used by physiotherapists to assess and treat muscles, joints, and soft tissues.',
  },
  {
    name: 'Cupping Therapy',
    shortDescription: 'Suction-cup technique for soft tissues.',
    description: 'Cupping therapy is a hands-on technique that uses suction cups placed on the skin to create a gentle vacuum effect.',
  },
  {
    name: 'Dry Needling',
    shortDescription: 'Targeted support for tight muscles.',
    description: 'If you’re dealing with persistent muscle tightness or movement limitations, dry needling can support recovery and improve how your body functions.',
  },
  {
    name: 'Spinal Manipulation / Adjustment',
    shortDescription: 'Mobility-focused spinal joint approach.',
    description: 'Spinal manipulation/adjustment is a hands-on approach focused on improving the mobility of the spine and supporting overall musculoskeletal function.',
  },
  {
    name: 'Electrotherapeutic Modalities',
    shortDescription: 'Electrical modalities used in rehabilitation.',
    description: 'Electrotherapeutic modalities are widely used in physiotherapy to support recovery, reduce discomfort, and improve muscle and nerve function.',
  },
  {
    name: 'Vestibular Therapy',
    shortDescription: 'Support for dizziness and balance concerns.',
    description: 'If you often feel dizzy, unsteady, or experience spinning sensations, it can interfere with daily activities and reduce confidence in movement.',
  },
  {
    name: 'Return to Work / Play',
    shortDescription: 'Structured return to activity after injury.',
    description: 'Returning to your daily routine after an injury can feel overwhelming. Whether your goal is getting back to your job, sport, or active lifestyle, having the right support makes a significant difference.',
  },
  {
    name: 'Myofascial Release',
    shortDescription: 'Hands-on work for tightness and mobility.',
    description: 'Tight muscles, lingering soreness, and limited movement can affect your daily routine more than you might expect.',
  },
  {
    name: 'Therapeutic Exercise',
    shortDescription: 'Guided strength and movement programs.',
    description: 'Therapeutic exercise plays a key role in improving movement, building strength, and supporting recovery from injury or physical strain.',
  },
  {
    name: 'Trigger Point Release',
    shortDescription: 'Focused manual work on trigger points.',
    description: 'Is muscle tightness and persistent soreness disrupting your daily life or limiting your movement? Trigger point release offers a focused manual therapy approach that targets specific areas of muscle tissue known as trigger points.',
  },
  {
    name: 'Dancer Rehabilitation',
    shortDescription: 'Rehabilitation tailored to dance demands.',
    description: 'Dancers place unique demands on their bodies, combining strength, flexibility, and precision in every movement.',
  },
  {
    name: 'Psychological Services',
    shortDescription: 'Mental and emotional wellness support.',
    description: 'Mental and emotional health play a major role in how you move, think, and live each day.',
  },
  {
    name: 'McKenzie Method',
    shortDescription: 'Movement-based approach for spine and joints.',
    description: 'If you are dealing with ongoing back, neck, or joint discomfort, finding the right approach can make a significant difference in how you move and function each day.',
  },
  {
    name: 'Deep Tissue Massage',
    shortDescription: 'Deeper pressure for persistent tightness.',
    description: 'If persistent muscle tightness or stiffness is interfering with your daily routine, deep tissue massage can play a key role in restoring movement and easing discomfort.',
  },
  {
    name: 'Soft Tissue Release',
    shortDescription: 'Hands-on work for restricted soft tissues.',
    description: 'Soft tissue release is a hands-on technique used to address tight muscles, restricted movement, and discomfort caused by everyday strain, sports activity, or prolonged sitting.',
  },
  {
    name: 'Relaxation Method',
    shortDescription: 'Stress and physical tension support.',
    description: 'Finding time to unwind has become increasingly difficult in a fast-paced city. Ongoing stress, physical tension, and mental fatigue can gradually affect how your body feels and performs.',
  },
].map((s, i) => ({
  _id: s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
  slug: s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
  name: s.name,
  shortDescription: s.shortDescription,
  description: s.description,
  image: SERVICE_IMAGES[i % SERVICE_IMAGES.length],
}))

export const PLACEHOLDER_TEAM = [
  {
    _id: 't1',
    slug: 'shyamli-patel',
    name: 'Shyamli Patel',
    role: 'Registered Physiotherapist',
    seniorTitle: 'Sr. Registered Physiotherapist',
    yearsExperience: 7,
    specialization: 'Physiotherapy',
    photo: '/team2.jpg',
    qualifications: ['Registered Physiotherapist'],
    bio: 'Shyamli has 7 years of experience helping patients recover movement and function through personalized physiotherapy.',
    expertise: ['Physiotherapy', 'Manual Therapy', 'Rehabilitation'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
  {
    _id: 't2',
    slug: 'dr-james-pascual',
    name: 'Dr. James Pascual',
    role: 'Chiropractor',
    seniorTitle: 'Chiropractor',
    yearsExperience: 25,
    specialization: 'Chiropractic Care',
    photo: '/Dr.-James-scaled-1.jpg',
    qualifications: ['Chiropractor'],
    bio: 'Dr. Pascual brings 25 years of experience in spine, joint and mobility-focused chiropractic care.',
    expertise: ['Chiropractic Care', 'Spinal Manipulation', 'Mobility'],
    philosophy: 'I believe recovery is a partnership — every plan is built around the patient’s goals, not a generic protocol.',
  },
  {
    _id: 't3',
    slug: 'jason-li',
    name: 'Jason Li',
    role: 'Massage Therapist',
    seniorTitle: 'Massage Therapist',
    yearsExperience: 13,
    specialization: 'Massage Therapy',
    photo: '/team5.jpg',
    qualifications: ['Registered Massage Therapist'],
    bio: 'Jason has 13 years of experience providing massage therapy for muscle tension and relaxation support.',
    expertise: ['Massage Therapy', 'Deep Tissue Massage', 'Relaxation Method'],
    philosophy: 'Pain relief should be holistic — treating the whole person, not just the symptom.',
  },
  {
    _id: 't4',
    slug: 'monali-chhodvadiya',
    name: 'Monali Chhodvadiya',
    role: 'Registered Physiotherapist',
    seniorTitle: 'Registered Physiotherapist',
    yearsExperience: 4,
    specialization: 'Musculoskeletal Conditions',
    photo: 'https://ui-avatars.com/api/?name=Monali+Chhodvadiya&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Registered Physiotherapist'],
    bio: 'Monali has 4 years of experience treating musculoskeletal conditions with personalized physiotherapy.',
    expertise: ['Physiotherapy', 'Musculoskeletal Conditions'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
  {
    _id: 't5',
    slug: 'deena-paul',
    name: 'Deena Paul',
    role: 'Physiotherapy Assistant',
    seniorTitle: 'Physiotherapy Assistant',
    yearsExperience: 5,
    specialization: 'Fibromyalgia',
    photo: 'https://ui-avatars.com/api/?name=Deena+Paul&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Physiotherapy Assistant'],
    bio: 'Deena has 5+ years of experience supporting patients managing fibromyalgia and chronic pain.',
    expertise: ['Physiotherapy', 'Fibromyalgia'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
  {
    _id: 't6',
    slug: 'dharini-vaghela',
    name: 'Dharini Vaghela',
    role: 'Resident Physiotherapist',
    seniorTitle: 'Registered Physiotherapist',
    yearsExperience: 4,
    specialization: 'Resident Physiotherapist',
    photo: 'https://ui-avatars.com/api/?name=Dharini+Vaghela&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Resident Physiotherapist'],
    bio: 'Dharini has 4+ years of experience as a resident physiotherapist.',
    expertise: ['Physiotherapy'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
  {
    _id: 't7',
    slug: 'harshdeep-patel',
    name: 'Harshdeep Patel',
    role: 'Resident Physiotherapist',
    seniorTitle: 'Resident Physiotherapist',
    yearsExperience: 4,
    specialization: 'Resident Physiotherapist',
    photo: 'https://ui-avatars.com/api/?name=Harshdeep+Patel&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Resident Physiotherapist'],
    bio: 'Harshdeep has 4+ years of experience as a resident physiotherapist.',
    expertise: ['Physiotherapy'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
  {
    _id: 't8',
    slug: 'dr-maryam-hatamian',
    name: 'Dr. Maryam Hatamian',
    role: 'Chiropractor',
    seniorTitle: 'Chiropractor',
    yearsExperience: 18,
    specialization: 'Back Pain',
    photo: 'https://ui-avatars.com/api/?name=Maryam+Hatamian&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Chiropractor'],
    bio: 'Dr. Hatamian brings 18+ years of experience in chiropractic care with a focus on back pain.',
    expertise: ['Chiropractic Care', 'Back Pain'],
    philosophy: 'I believe recovery is a partnership — every plan is built around the patient’s goals, not a generic protocol.',
  },
  {
    _id: 't9',
    slug: 'selam-haile',
    name: 'Selam Haile',
    role: 'Registered Massage Therapist',
    seniorTitle: 'Registered Massage Therapist',
    yearsExperience: 2,
    specialization: 'Massage Therapy',
    photo: 'https://ui-avatars.com/api/?name=Selam+Haile&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Registered Massage Therapist'],
    bio: 'Selam has 2+ years of experience providing registered massage therapy.',
    expertise: ['Massage Therapy'],
    philosophy: 'Pain relief should be holistic — treating the whole person, not just the symptom.',
  },
  {
    _id: 't10',
    slug: 'luting-zheng',
    name: 'Luting Zheng',
    role: 'Physiotherapist',
    seniorTitle: 'Physiotherapist',
    yearsExperience: 7,
    specialization: 'Sports Injuries',
    photo: 'https://ui-avatars.com/api/?name=Luting+Zheng&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Physiotherapist'],
    bio: 'Luting has 7+ years of experience treating sports injuries through physiotherapy.',
    expertise: ['Physiotherapy', 'Sports Injuries'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
  {
    _id: 't11',
    slug: 'tahira-jibeen',
    name: 'Tahira Jibeen',
    role: 'Clinical Psychologist',
    seniorTitle: 'Clinical Psychologist',
    yearsExperience: null,
    specialization: 'Cognitive Behavioral Therapy',
    photo: 'https://ui-avatars.com/api/?name=Tahira+Jibeen&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Clinical Psychologist'],
    bio: 'Tahira provides cognitive behavioral therapy to support mental and emotional well-being.',
    expertise: ['Psychological Services', 'Cognitive Behavioral Therapy'],
    philosophy: 'Mental and emotional health play a major role in how you move, think, and live each day.',
  },
  {
    _id: 't12',
    slug: 'kamlesh-patel',
    name: 'Kamlesh Patel',
    role: 'Psychotherapist / Registered Social Worker',
    seniorTitle: 'Psychotherapist',
    yearsExperience: 18,
    specialization: 'Psychotherapy',
    photo: 'https://ui-avatars.com/api/?name=Kamlesh+Patel&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Psychotherapist', 'Registered Social Worker'],
    bio: 'Kamlesh has 18 years of experience as a psychotherapist and registered social worker.',
    expertise: ['Psychological Services'],
    philosophy: 'Mental and emotional health play a major role in how you move, think, and live each day.',
  },
  {
    _id: 't13',
    slug: 'anju-patel',
    name: 'Anju Patel',
    role: 'Clinic Administrator',
    seniorTitle: 'Clinic Administrator',
    yearsExperience: 6,
    specialization: 'Clinic Operations',
    photo: 'https://ui-avatars.com/api/?name=Anju+Patel&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Clinic Administrator'],
    bio: 'Anju has 6+ years of experience managing clinic operations and patient coordination.',
    expertise: ['Clinic Operations'],
    philosophy: 'A smooth, welcoming visit starts before you even walk through the door.',
  },
  {
    _id: 't14',
    slug: 'foram-patel',
    name: 'Foram Patel',
    role: 'Physiotherapy Assistant',
    seniorTitle: 'Physiotherapy Assistant',
    yearsExperience: 3,
    specialization: 'Rehabilitation',
    photo: 'https://ui-avatars.com/api/?name=Foram+Patel&background=D9C6A5&color=2B2118&size=400',
    qualifications: ['Physiotherapy Assistant'],
    bio: 'Foram has 3+ years of experience supporting rehabilitation programs.',
    expertise: ['Physiotherapy', 'Rehabilitation'],
    philosophy: 'Every patient deserves a plan built on evidence, patience, and genuine care.',
  },
]


export const PLACEHOLDER_TESTIMONIALS = [
  {
    _id: 'r1',
    name: 'Amanda K.',
    testimonial: 'After months of chronic back pain, the team at Markham Pain Clinic finally gave me a plan that worked. I am pain-free and back to my morning runs.',
    rating: 5,
    serviceCategory: 'Physiotherapy',
  },
  {
    _id: 'r2',
    name: 'David R.',
    testimonial: 'Professional, caring, and genuinely invested in my recovery. My shoulder injury healed faster than I expected.',
    rating: 5,
    serviceCategory: 'Sports Injury Rehabilitation',
  },
  {
    _id: 'r3',
    name: 'Priya S.',
    testimonial: 'The acupuncture sessions completely changed how I manage my migraines. Highly recommend this clinic to anyone in pain.',
    rating: 5,
    serviceCategory: 'Acupuncture & Dry Needling',
  },
  {
    _id: 'r4',
    name: 'Tom H.',
    testimonial: 'I appreciated how personalized every session felt. They listened, adjusted the plan, and got real results.',
    rating: 4,
    serviceCategory: 'Chronic Pain Management',
  },
]

export const PLACEHOLDER_BLOGS = [
  {
    _id: 'b1',
    slug: 'five-signs-you-need-physiotherapy',
    title: '5 Signs You May Need Physiotherapy',
    category: 'Physiotherapy',
    excerpt: 'Persistent pain or stiffness could be signs your body needs professional attention. Here is what to watch for.',
    content:
      'Persistent pain, reduced range of motion, recurring injuries, poor posture, and slow recovery after activity are all signs that physiotherapy could help. Early intervention often leads to faster, more complete recovery than waiting for symptoms to worsen. Our team can assess your specific situation and design a plan tailored to your goals.',
    featuredImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1200&auto=format&fit=crop',
    createdAt: '2026-06-12',
  },
  {
    _id: 'b2',
    slug: 'understanding-chronic-pain',
    title: 'Understanding Chronic Pain: Causes and Coping Strategies',
    category: 'Chronic Pain',
    excerpt: 'Chronic pain affects millions. Learn about its causes and evidence-based ways to manage it long-term.',
    content:
      'Chronic pain is defined as pain lasting longer than three months and can stem from injury, illness, or unknown causes. Effective management often combines physical therapy, gentle movement, stress reduction, and professional guidance rather than relying on a single solution.',
    featuredImage: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?q=80&w=1200&auto=format&fit=crop',
    createdAt: '2026-05-28',
  },
  {
    _id: 'b3',
    slug: 'benefits-of-acupuncture',
    title: 'The Science-Backed Benefits of Acupuncture',
    category: 'Acupuncture',
    excerpt: 'Acupuncture is more than tradition — modern research supports its role in pain management.',
    content:
      'Modern research shows acupuncture can stimulate the nervous system, release natural pain-relieving chemicals, and improve blood flow to affected areas. Combined with dry needling techniques, it is a powerful, drug-free option for many types of pain.',
    featuredImage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1200&auto=format&fit=crop',
    createdAt: '2026-05-10',
  },
]

export const PLACEHOLDER_FAQS = [
  { _id: 'f1', question: 'Do I need a referral to book an appointment?', answer: 'No referral is required. You can book directly with us, though a referral from your doctor is welcome if you have one.' },
  { _id: 'f2', question: 'What should I expect at my first appointment?', answer: 'Your first visit includes a thorough assessment of your condition, medical history review, and the start of a personalized treatment plan.' },
  { _id: 'f3', question: 'How long is each treatment session?', answer: 'Most sessions run between 30 and 60 minutes depending on the treatment type and your individual plan.' },
  { _id: 'f4', question: 'What conditions do you treat?', answer: 'We treat back and neck pain, sports injuries, chronic pain, joint issues, postural problems, and more.' },
  { _id: 'f5', question: 'How many treatments will I need?', answer: 'This varies by condition and severity. Your therapist will discuss an estimated timeline after your initial assessment.' },
  { _id: 'f6', question: 'Do you treat sports injuries?', answer: 'Yes, we offer dedicated sports injury rehabilitation programs for athletes of all levels.' },
  { _id: 'f7', question: 'Can you help with chronic, long-term pain?', answer: 'Absolutely. We specialize in whole-person chronic pain management plans built for long-term results.' },
  { _id: 'f8', question: 'How do I book an appointment?', answer: 'You can call us, email us, or use the contact form on this website and our team will reach out to schedule your visit.' },
]

export const PLACEHOLDER_CONDITIONS = [
  { name: 'WSIB Injuries' },
  {
    name: 'Motor Vehicle Accident Injuries',
    description: 'Motor vehicle accident injuries can disrupt daily life in both immediate and long-lasting ways.',
  },
  {
    name: 'Fibromyalgia Treatment',
    description:
      'Fibromyalgia is a complex condition that affects how the body processes pain signals, leading to widespread discomfort.',
  },
  {
    name: 'Dizziness Treatment',
    description: 'Dizziness can interfere with everyday activities, making simple movements like walking, turning your head, or even standing up feel unsteady.',
  },
  {
    name: 'Chronic Pain',
    description: 'Living with chronic pain can affect every part of your daily life, from work and sleep to movement and mood.',
  },
  {
    name: 'Balance Disorder',
    description: 'Balance plays a vital role in everyday life, from simple movements like walking to more complex activities such as exercising.',
  },
  {
    name: 'Hand Pain',
    description: 'Hand pain can make even simple daily tasks feel difficult. From typing and writing to lifting objects or gripping tools, discomfort can get in the way.',
  },
  { name: 'Elbow Pain' },
  { name: 'Ankle Pain' },
  { name: 'Dance Injuries' },
  { name: 'Hip Pain' },
  { name: 'Sciatica Pain' },
  { name: 'Headaches' },
  { name: 'Vertigo' },
  { name: 'Concussions' },
  { name: 'Gait Disorders' },
  { name: 'Arthritis Treatment' },
  { name: 'Wrist Pain' },
  { name: 'Shoulder Pain' },
  { name: 'Foot Pain' },
  { name: 'Knee Pain' },
  { name: 'Neck Pain' },
  { name: 'Back Pain' },
].map((c, i) => ({ _id: `c${i}`, ...c }))

export const PLACEHOLDER_STATS = [
  { _id: 's1', label: 'Patients Helped', value: 5000, suffix: '+' },
  { _id: 's2', label: 'Years of Experience', value: 15, suffix: '+' },
  { _id: 's3', label: 'Patient Satisfaction', value: 98, suffix: '%' },
]

export const CLINIC_INFO = {
  phone: '+1 905-243-9423',
  email: 'itssiddharthpatel@gmail.com',
  instagram: '@Markhampainclinic',
  instagramUrl: 'https://instagram.com/Markhampainclinic',
  address: '8 Shadlock St #1, Markham, ON L3S 3K9, Canada',
  hours: 'Open 7 Days a Week',
  businessName: 'Markham Pain Clinic',
}
